"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import pymysql

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(u3^zq%@ryf3beby1q)^9tq6k7uj00x9#(p5#xhkjns1m@i3l_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',  # admin管理后台站点
	'django.contrib.auth',  # 身份认证系统
	'django.contrib.contenttypes',  # 内容类型框架
	'django.contrib.sessions',  # 会话框架
	'django.contrib.messages',  # 消息框架
	'django.contrib.staticfiles',  # 静态文件管理框架

	'cmdb',
	'polls',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	# 'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',  # 后端
		'DIRS': [os.path.join(BASE_DIR, 'templates')],  # 文件系统目录的列表，是模板的搜索路径
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases


DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		# ENGINE（引擎）  是
		# django.db.backends.sqlite3、
		# django.db.backends.postgresql、
		# django.db.backends.mysql、
		# django.db.backends.oracle，当然其它的也行
		'NAME': 'mysite',  # 类似Mysql数据库管理系统中用于保存项目内容的数据库的名字
		'HOST': 'localhost',
		'USER': 'root',
		'PASSWORD': 'sulong@20161010',
		'PORT': '3306',
	}
}
# DATABASES = {
# 	'default': {
# 		'ENGINE': 'django.db.backends.sqlite3', # 指定使用的数据库类型
# 		'NAME': os.path.join(BASE_DIR, 'db.sqlite3'), #  django自带轻量级数据库sqlite3
# 	}
# }

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh_Hans'

TIME_ZONE = 'Asia/Shanghai'  # 设置时区

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'  # 引用指针 不是具体的目录 需要在 html文件中与之对应

STATICFILES_DIRS = (
	os.path.join(BASE_DIR, 'static'),  # 元组 都好不可省略
)

MEDIA_ROOT = '/Users/sulong/'  # 上传文件 在服务器中的基本路径（为了性能考虑，这些文件不会被储存在数据库中）

MEDIA_URL = '/Users/sulong/uploads/'  # 指向上传文件的基本路径
